### ISSUE TITLE
Logs are not available in NR when using the nt-otlp-exporter example

### ISSUE THREAD

**Issue by jenarros-lw** [newrelic/newrelic-opentelemetry-examples#105]
I am trying to test the example from: https://github.com/newrelic/newrelic-opentelemetry-examples/blob/main/collector/nr-otlp-export/otel-config.yaml

The only difference is that logs are sent to the collector via the **otlp** receiver instead of fluentforward. Then as per the example, we use **otlp** to export the logs to New Relic.

I can see metrics in NR as well as logging out of the container from the logs->logging exporter so the logs are being received by the collector.

However, we cannot see any logs in NR, only the metrics and traces, it seems that the NR otlp exporter is not exporting the logs to NR and there are no errors in the container logs.

I wanted to check if this example fully works and we should be able to see the logs in NR. If so, do you know how we could identify what may be going wrong?

**Comment by jenarros-lw** [comment]
Hi @jack-berg, I am trying to find the logs via `Services - OpenTelemetry -> <service.name> -> Logs` but it says there are no logs at all.

**Comment by jack-berg** [comment]
This is unexpected and I'm looking into it. Can you confirm that you aren't seeing any errors in the logs of the collector?

**Comment by jenarros-lw** [comment]
Yes, these are the logs of the collector:
[logs.txt](https://github.com/newrelic/newrelic-opentelemetry-examples/files/8421323/logs.txt)

**Comment by jack-berg** [comment]
We've been looking into this internally and are not able to recreate it or see any obvious issue with your configuration or account that would explain why the logs are missing. Couple of thoughts:

- We noticed that there are couple of drop rules configured in your account. It's a bit of a longshot, but would it be possible for you to try again with the drop rules temporarily disabled?
- Are you able to see logs in New Relic if you run `sdk-nr-config` configured to export directly to New Relic? I.e. without a collector intermediate hop.  
- With your permission I could attempt to run the example from your account, which would allow us to better debug the situation.

**Comment by jenarros-lw** [comment]
Thanks @jack-berg for looking at this, I think drop rules may have been the issue. I am now able to see logs in NR going via the collector.

Thanks again for your help!
