### ISSUE TITLE
The Go example should include Logs and any configuration needed to support Logs in Context

### ISSUE THREAD

**Issue by jsgithub1** [newrelic/newrelic-opentelemetry-examples#151]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

The existing Go example does not include Logs or support for "logs in context" with its traces.  It is included for other languages, like Java.  We should add it for Go as well.

## Desired Behavior

The Go example should demonstrate capturing and forwarding of Log information, along with any necessary configuration so that Logs can be correlated with traces ("logs in context").

**Comment by TylerHelmuth** [comment]
Can you detail out what New Relic requires to make "Logs in Context" work?  If we add this example scenario we'll add it for all languages.

**Comment by alanwest** [comment]
When the Go SDK supports logs we'll be sure to add examples that demonstrate it.
