### ISSUE TITLE
Golang opentelemetry sdk doesn't support delta aggregations with PrecomputedSum

### ISSUE THREAD

**Issue by veqryn** [newrelic/newrelic-opentelemetry-examples#156]
See notes here: https://github.com/open-telemetry/opentelemetry-go/issues/2868

The current example has a temporality selector that forces CounterObserver to use delta temporality, which causes the opentelemetry sdk to throw errors and not export the metric.

**Comment by TylerHelmuth** [comment]
I agree.  If I add an CounterObserver to the `metrics.go` example it will print out "cumulative to delta not implemented" and not export the metric.

This is a limitation with the Go Metrics SDK, which isn't stable yet.  Being able to set delta temporality for Async Counters is part of the otel specification, though, so I would expect the capability to be added before a stable Go metrics SDK release.

For this example, if we switch `CounterObserverInstrumentKind` to delta then New Relic will treat the data as a Gauge, which is slightly misleading.

**Comment by TylerHelmuth** [comment]
Guess that is better than an error though.  I will update the temporality selector so that an error is not thrown.  When the Go SDK supports delta temporality for these instruments in the future I will add it back.
