### ISSUE TITLE
Dotnet example not working

### ISSUE THREAD

**Issue by petrkoutnycz** [newrelic/newrelic-opentelemetry-examples#175]
## Description

There are no data in New Relic UI.
## Steps to Reproduce

I downloaded the repo, set env variables and ran the dotnet project. I dont see any data in New Relic UI whatsoever. There are no bugs in console, no exceptions.

## Expected Behavior

I see traces, logs and metrics in UI.

## Your Environment

Rider IDE
Following .NET SDKs are installed
![image](https://user-images.githubusercontent.com/9723402/191185076-1aba44b8-94ac-420b-8533-70d577bc1df3.png)

**Comment by alanwest** [comment]
Are you referring to this example? https://github.com/newrelic/newrelic-opentelemetry-examples/tree/main/dotnet/aspnetcore

If so, the .NET SDK has some self-diagnostics you can enable to help identify any issues. https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry#self-diagnostics

**Comment by petrkoutnycz** [comment]
Yes, I am referring to that page. Okay, I will give it a shot. Thank you.
