### ISSUE TITLE
Ruby example does not work

### ISSUE THREAD

**Issue by friendlyantz** [newrelic/newrelic-opentelemetry-examples#526]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
as per docs
```
export OTEL_EXPORTER_OTLP_HEADERS=api-key=LICENSE_INGEST_KEY
export OTEL_SERVICE_NAME=anton-test-otlp # matches name of license key from above in NewRelic
export OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.nr-data.net:PORT # tried both 443 and 4317 (4317 is as per docs, which I believe it is gRPC port and is incorrect. refer error logs below)

bundle exec rackup
 ./load-generator.sh
```
[NewRelic docs FYI](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-set-up-your-app/#note-ports)

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
1. entity created in NewRelic with `anton-test-otlp` name
2. see data in NewRelic UI for these queries
```
FROM Log SELECT count(*) where newrelic.source='%otlp%' TIMESERIES
or
FROM Metric SELECT count(*) where newrelic.source LIKE '%otlp%' TIMESERIES
or
FROM Span SELECT count(*) where newrelic.source='%otlp%' TIMESERIES

```

## Relevant Logs / Console output

for port`4317` (which I believe is incorrect and used for gRPC):
```
E, [2024-01-18T18:12:28.465831 #1092] ERROR -- : OpenTelemetry error: unexpected error in OTLP::Exporter#send_bytes - Failed to open TCP connection to otlp.nr-data.net:4317 (connect(2) for "otlp.nr-data.net" port 4317)
E, [2024-01-18T18:12:28.465957 #1092] ERROR -- : OpenTelemetry error: Unable to export 10 spans
```

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

MacOS latest OS, M2

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by kaylareopelle** [comment]
Hi @friendlyantz! I'm sorry to hear you're running into trouble. Could you try removing the port from the `OTEL_EXPORTER_OTLP_ENDPOINT` and see what happens? 

Your comment is timely, as yesterday https://github.com/newrelic/newrelic-opentelemetry-examples/pull/524, was opened which removes port 4317 from the README. This PR is now merged.

Also, OpenTelemetry Ruby does not yet have support for Metrics or Logs, so you'll only see Traces/Spans come through.

If you're willing to use experimental code, I can help you get started with automatic log forwarding. Metrics is a bit trickier, but we also have some experimental forwarding available for a very limited feature set without automatic instrumentation.

**Comment by kaylareopelle** [comment]
One other thing -- you'll need to update your query to use `LIKE` instead of `=`, for example: 

`FROM Span SELECT count(*) where newrelic.source LIKE '%otlp%' TIMESERIES`

**Comment by friendlyantz** [comment]
Fantastic! I managed to get the data to NewNelic! Thank you very much! 🎉 
I would love to experiment with log forwarding for sure, and keen to experiment with metrics as well!
Many thanks
