### ISSUE TITLE
Remove `cumulativetodelta` in collector example

### ISSUE THREAD

**Issue by csalvador-nr** [newrelic/newrelic-opentelemetry-examples#650]
Since New Relic now supports [cumulative metrics](https://docs.newrelic.com/docs/data-apis/understand-data/metric-data/cumulative-metrics/), is this still necessary?

https://github.com/newrelic/newrelic-opentelemetry-examples/blob/a55fb8923bc1529eea0398d8cd81e25654e3b13b/other-examples/collector/nr-config/otel-config.yaml#L10-L13

**Comment by jack-berg** [comment]
Yes, from our docs: https://docs.newrelic.com/docs/opentelemetry/best-practices/opentelemetry-otlp/#metric-aggregation-temporality

> While New Relic supports cumulative aggregation temporality, the New Relic metrics architecture is generally a delta metrics system. Using the default cumulative setting will generally incur more memory usage from SDKs and result in high data ingest.
