### ISSUE TITLE
Wanted: A nodejs and grpc-js example

### ISSUE THREAD

**Issue by lamroger** [newrelic/newrelic-opentelemetry-examples#74]
## Summary

Hey! A nodejs and grpc-js example would be great. It's hard to see why traces aren't being sent to NR and an example could help avoid super simple issues.

**Comment by alanwest** [comment]
Hey @lamroger, thanks for the request! Good news, we're looking to expand these examples to all languages soon. In fact, @svetlanabrennan is working on a basic nodejs example right now demonstrating how to send data to New Relic.

Regarding grpc-js, do you mean an example of a service that makes or receives gRPC calls?

**Comment by svetlanabrennan** [comment]
Hi @lamroger, 

Here's our [nodejs](https://github.com/newrelic/newrelic-opentelemetry-examples/tree/main/javascript/simple-nodejs-app) example using gRPC. 

If you have any other questions, please feel free to open another issue. Thanks!

**Comment by lamroger** [comment]
thanks for the quick turnaround!
