### ISSUE TITLE
Add a basic Python example

### ISSUE THREAD

**Issue by alanwest** [newrelic/newrelic-opentelemetry-examples#79]
We need this example to demonstrat use of Python's OTLPSpanExporter. See: https://opentelemetry-python.readthedocs.io/en/latest/exporter/otlp/otlp.html.

Depending on how far a long the OpenTelemetry Python project is with metric and log support, it would be great to demonstrate these as well.

@reese-lee is this something you can take a look at?

**Comment by reese-lee** [comment]
There are two examples [here](https://github.com/newrelic/newrelic-opentelemetry-examples/tree/main/python/python-examples): one service that generates spans, and another that does the same but includes the web framework Flask. 

Going to look into metrics next.

**Comment by TylerHelmuth** [comment]
If this is still needed I can work on it

**Comment by reese-lee** [comment]
@TylerHelmuth That would be great if we can partner on this! What I have is super basic at the moment, and we could definitely use more robust examples.
